### ISSUE TITLE
Handle authentication properly.

### ISSUE THREAD

**Issue by miskibin** [miskibin/sejmofront#7]
We are using supabase auth. (with oauth providers only)
Currently after user is logged in he is always redirected to home page. 

We want to redirect user to the place where he was.
Moreover if user added reaction (this is feature for logged users only) 
1. He should see login-dialog
2. After he is successfully logged in, he should be taken into place where he left 
3. reaction should be added. 

We are using self hosted supabase wiht config like this:

```yaml
services:
  auth:
    environment:
      # Base URL of your website
      GOTRUE_SITE_URL: "https://sejmofil.pl"

      # Enable GitHub as an external provider
      GOTRUE_EXTERNAL_GITHUB_ENABLED: "true"

      # GitHub OAuth Client ID
      GOTRUE_EXTERNAL_GITHUB_CLIENT_ID: "secret"

      # GitHub OAuth Client Secret
      GOTRUE_EXTERNAL_GITHUB_SECRET: "secret"

      # GitHub OAuth Redirect URI
      GOTRUE_EXTERNAL_GITHUB_REDIRECT_URI: "https://db.msulawiak.pl/auth/v1/callback"

      # List of allowed redirect URIs
      GOTRUE_URI_ALLOW_LIST: ["https://sejmofil.pl/*"]

      # Token expiration time in seconds (optional; default: 3600)
      GOTRUE_JWT_EXP: "3600"

      # Disable signups (optional; set to true if you want to restrict new signups)
      GOTRUE_DISABLE_SIGNUP: "false"

      # Disable email signup (since you are using only GitHub auth)
      GOTRUE_EXTERNAL_EMAIL_ENABLED: "false"

      # Auto-confirm email addresses (optional; you can leave it as true for GitHub auth)
      GOTRUE_MAILER_AUTOCONFIRM: "true"
```
